### ISSUE TITLE
关于commit message的疑惑

### ISSUE THREAD

**Issue by pwyq** [wanghusw/wanghusw.github.io#1]
你好。
我看见你的commit message都是`Site updated: yyyy-mm-dd`的格式；而一般的github repo的commit message都是`add sth` `fix a bug`。
对此我感到很困惑，所以想请问一下你是用什么工具生成的呢？谢谢了。

**Comment by wanghusw** [comment]
你好，我用的是 hexo 搭建的博客，用 git bash 提交之后，commit message 应该是自动生成的，我并没有进行任何的干预。

**Comment by pwyq** [comment]
谢谢。
